---
title: "clase 3"
author: "Pep Matemales"
date: "26/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## VECTORES

```{r}
c(1,2,3)
```


```{r}
bolas=c(rep("Roja",7), rep("Azul",3))
bolas
```

```{r}
año=c(rep(2001,10))
```

```{r}
vec=c(16,0,1,20,1,7,88,5,1,9)
vec
```



```{r}
1:20
```
```{r}
seq(2,by=2,length.out = 20)
```


```{r}
round(seq(17,98,length.out = 30), 3)
```

```{r}
x=1:10
sapply(x,FUN = sin)
length(x)
max(x)
min(x)
sum(x)
prod(x)
mean(x)
diff(x)
cumsum(x)

```

```{r}
cuadrao=function(x){x^2}
v=c(1,2,3,4,5,6)
sapply(v, FUN = cuadrao)
cuadrao(v)
```

```{r}
gg=c(1,77,4,9,54,12)
sort(gg)
gg_revertido=rev(gg)
rev(sort(gg))
gg_revertido
```

```{r}
gg[2]
gg_revertido[2:5]
```
```{r}
x
x[-3]
x[-(3:5)]
x[-c(3,5)]
x[x%%2==0]
x[!(x%%2==0)]
```

```{r}
z=c(x,1,1,10,10)
z
which.min(z)
which.max(z)
#which(z==max) no van
#which(z==min)
```



```{r}
fac=factor(c(1,1,1,2,3,3,2,2,3,4,3,3,1,4),levels=c(1,2,3,4,5),
           labels=c("Sus","Apr","Not","Exc","MH"))
fac

```

```{r}
t=c(1,3,6,-7,8,3,-4,7,8,8)
t
lista=list(nombre="T", vector=t, media=mean(t), sumas=cumsum(x))
str(lista)
```


```{r}
M=matrix(1:9, nrow=3, byrow = TRUE)
N=matrix(1:9, nrow=3, byrow = FALSE)
M
N
```

```{r}
rbind(c(1,5,3),c(2,6,3))
diag(c(1,2,3,4,5))
```

```{r}
A=matrix(1:9, nrow=3, byrow = TRUE)
A
A[1,3]
A[3,1]
A[1,]
A[,1]
A[1:3,2:3]
diag(A)
dim(A)
colSums(A)
rowSums(A)
rowMeans(A)
```

```{r}
B=matrix(1:9, nrow=3, byrow = TRUE)
apply(B,MARGIN = c(1,2), FUN = cuadrao)
apply(B, MARGIN = 1, FUN=sum)
```

```{r}
#operciones con matrices y mas cosas



```







