---
title: "Tema6-2"
author: "Pep Matemales"
date: "29/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Datos multidimensionales (no esta en apuntes)

## Ejemplo con tres dimensiones

```{r}
ans = sample(c("Si", "No"), size = 100, replace = TRUE)
sex = sample(c("H", "M"), size = 100, replace = TRUE)
place = sample(c("San Francisco", "Barcelona", "Valencia", "Cobija", "Asturias"), size = 100, replace = TRUE)

table(sex, ans, place) #te hace las tablas bidimensionales de los place

ftable(sex, ans, place)
ftable(sex, ans, place, col.vars = c("sex", "ans")) #para que en las columnas aparezcan sex y ans
```


### Filtrar las tablas

```{r}
table(sex, ans, place)["M", "Si", "San Francisco"]
table(sex, ans, place)[ , "Si", "Valencia"]
table(sex, ans, place)[ , "No", ]
table(sex, ans, place)["M", , "Cobija"]
```


### Frecuencias relativas 
```{r}
prop.table(table(sex, ans, place))#Frec. Rel. Globales
prop.table(table(sex, ans, place), margin = 3) # Frec. Rel. Marginal por Lugar
prop.table(table(sex, ans, place), margin = c(1, 3)) # Frec. Rel. Marg. por Sexo y País

ftable(prop.table(table(sex, ans, place)))
```



